// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx77ZtGUIaAremhdJ2oJuEN1mwQcWSce8',
    appId: '1:984833099168:web:b7e1b79d8e596673bcd0c5',
    messagingSenderId: '984833099168',
    projectId: 'jobtask-d1bac',
    authDomain: 'jobtask-d1bac.firebaseapp.com',
    storageBucket: 'jobtask-d1bac.firebasestorage.app',
    measurementId: 'G-E50VTTKN2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4njzrXI-nha0Szx94jhXG70lJadpC-FQ',
    appId: '1:984833099168:android:c1cab0ad5ca16281bcd0c5',
    messagingSenderId: '984833099168',
    projectId: 'jobtask-d1bac',
    storageBucket: 'jobtask-d1bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-dNMW1n1uREl0znbR2iDR5gjKmp6RGVA',
    appId: '1:984833099168:ios:fc717f9b749842e6bcd0c5',
    messagingSenderId: '984833099168',
    projectId: 'jobtask-d1bac',
    storageBucket: 'jobtask-d1bac.firebasestorage.app',
    iosBundleId: 'com.example.jobTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-dNMW1n1uREl0znbR2iDR5gjKmp6RGVA',
    appId: '1:984833099168:ios:fc717f9b749842e6bcd0c5',
    messagingSenderId: '984833099168',
    projectId: 'jobtask-d1bac',
    storageBucket: 'jobtask-d1bac.firebasestorage.app',
    iosBundleId: 'com.example.jobTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx77ZtGUIaAremhdJ2oJuEN1mwQcWSce8',
    appId: '1:984833099168:web:6cffc1bcff625d85bcd0c5',
    messagingSenderId: '984833099168',
    projectId: 'jobtask-d1bac',
    authDomain: 'jobtask-d1bac.firebaseapp.com',
    storageBucket: 'jobtask-d1bac.firebasestorage.app',
    measurementId: 'G-EH3S9B6STC',
  );
}
